// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleNavi: typeof import('./src/components/ArticleNavi.vue')['default']
    Categories: typeof import('./src/components/Categories.vue')['default']
    CommentInfo: typeof import('./src/components/CommentInfo.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    EditTag: typeof import('./src/components/EditTag.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MakeComment: typeof import('./src/components/MakeComment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SidebarRight: typeof import('./src/components/SidebarRight.vue')['default']
    StarryBackground: typeof import('./src/components/StarryBackground.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    WaveBackground: typeof import('./src/components/WaveBackground.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
